# System
[system]
pipewire = {}
pipewire-alsa = {}
pipewire-audio = {}
pipewire-jack = {}
pipewire-pulse = {}
gst-plugin-pipewire = {}
wireplumber = {}
pavucontrol = {}
pamixer = {}
networkmanager = {}
network-manager-applet = {}
bluez = {}
bluez-utils = {}
blueman = {}
brightnessctl = {}
unzip = {}

# Display Manager
[displaymanager]
sddm = {}
qt5-quickcontrols = {}
qt5-quickcontrols2 = {}
qt5-graphicaleffects = {}

# Window Manager
[windowmanager]
hyprland = {}
dunst = {}
rofi-lbonn-wayland-git = {}
waybar = {}
swww = {}
swaylock-effects-git = {}
wlogout = {}
grimblast-git = {}
hyprpicker = {}
slurp = {}
swappy = {}
cliphist = {}


# Theming
[theming]
nwg-look = {}
qt5ct = {}
qt6ct = {}
kvantum = {}
qt5-wayland = {}
qt6-wayland = {}

# Applications
[extra.applications]
firefox = {}
kitty = {}
dolphin = {}
ark = {}
appimagelauncher = {}


[extra.editor]
neovim = {}
visual-studio-code-bin = {}
code = {}
sublime-text4 = {}
# Shell
[shell]
# Choose one option for file lister
eza = {} # or
# lsd = {}  # uncomment if desired

# Choose one option for shell (and optionally theme)
zsh = {}
oh-my-zsh-git = {}           # plugin manager (required for theme)
zsh-theme-powerlevel10k = {} # theme (requires oh-my-zsh-git)

# starship = {}  # uncomment for fish and its theme

neofetch = {}
pokemon-colorscripts-git = {} # uncomment if desired

# Hyprdots
[hyprdots]
hyprdots-ctl-git = {}
